

services:
  api:
    build: .
    container_name: voice_journal_api
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: voice_journal_api_db
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
